run: main.c
	gcc -o main.exe -lm main.c
	./main.exe
clean:
	-rm -f main.exe 2>/dev/null || true
	-rm -f *.s 2>/dev/null || true
	-rm -f *.o 2>/dev/null || true
	-rm -f *.out 2>/dev/null || true
	-rm -f *.elf 2>/dev/null || true
	-rm -f *.bin 2>/dev/null || true
